// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxbykfgheniybnncvzjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YnlrZmdoZW5peWJubmN2emp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjcyMzgsImV4cCI6MjA2NzQ0MzIzOH0.l6RAMI7uwAufQIeP5NGA_NoHI_-P95qPJCp5wD6M5tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});